//1. Assign by hand same value to 3 variables in binary, octal and hexadecimal format.

let binaryVar = 0b1000;
console.log(binaryVar); // =8

let octalVar = 0755;
console.log(octalVar); // =493

let hexademicalVar = 0XA;
console.log(hexademicalVar); // =10

//2. Implement function `extractNumbers` which will leave only numbers in passed string.

function extractNumbers (text) {
  let numbersOnly = text.replace(/\D+/g, "");
  console.log(numbersOnly);
}

extractNumbers('23123gfdhfhgf00998');

//3. Declare a variable with decimal value and convert to binary, octal and hexadecimal.

const decimalValue = 100;

const binaryValue = decimalValue.toString(2); // = "1100100"
const octalValue = decimalValue.toString(8); // = "144"
const hexValue = decimalValue.toString(16); // = "64"

//4. use `Math.random` to generate random value from `0` to `100`.

let min = 0;
let max = 100;

let randomFromZeroToOneHundred = Math.floor(Math.random() * (max - min + 1)) + min;

console.log(randomFromZeroToOneHundred);

//# Additional

//1. Make function which will take a array with numbers as a parameter and
   //calculate average number and round to hundredths.

var myArray = [0, 1, 2, 3, 4, 5, 444, 7, 8, 9, 10, 11];

function averageNumber(myArray) {
    let total = 0;
    for (let i = 0; i < myArray.length; i++) {
        total += myArray[i];
    }
        console.log(Math.round(total/myArray.length));
}

averageNumber(myArray);

// Average number function with usage of reduce method

function averageNumber2(myArray) {
  let total = myArray.reduce((total, amount) => total + amount);
  console.log(Math.floor(total/myArray.length));
}

averageNumber2(myArray);

//2. Generate array to pass to function above with values, and length generated by Math.random
let myArrayRandom = Array.from({length: 40}, () => Math.floor(Math.random() * 40));
console.log(myArrayRandom);
